spring:
  application:
    name: shinecart

  datasource:
    url: ${DB_URL:jdbc:postgresql://localhost:5432/shinecart}
    username: ${DB_USERNAME:postgres}
    password: ${DB_PASSWORD:password}
    driver-class-name: org.postgresql.Driver

  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect

  servlet:
    multipart:
      enabled: true
      max-file-size: 10MB
      max-request-size: 50MB

  mail:
    host: smtp.gmail.com
    port: 587
    username: ${MAIL_USERNAME}
    password: ${MAIL_PASSWORD}
    properties:
      mail:
        smtp:
          auth: true
          starttls:
            enable: true

server:
  port: 8080

jwt:
  secret: ${JWT_SECRET}
  expiration: 86400000   # 24 hours


# Razorpay Configuration
razorpay:
  key:
    id: ${RAZORPAY_KEY}
    secret: ${RAZORPAY_SECRET}
  currency: INR


logging:
  level:
    org.springframework.security: DEBUG
    org.springframework.web: DEBUG